import './globals.css'
import SideNav  from '@/components/side-nav'

export const metadata = {
    title: 'Hospital Dashboard',
    description: 'Generated by Next.js',
}
  
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <SideNav/>
        <body>
          <main className='ml-64 p-4'>
            {children}
          </main>
        </body>
      </html>
    )
  }